import type { Metadata } from "next";
import { El_Messiri,  } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";


const elMessiri = El_Messiri({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
     >
      <body className={`min-h-full flex flex-col ${elMessiri.className}`}>
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
